FROM alpine as builder
ARG VERSION=0.12.0
ADD https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v${VERSION}/otelcontribcol_linux_arm64 /
RUN chmod 755 /otelcontribcol_linux_arm64
FROM otel/opentelemetry-collector:0.13.0
COPY --from=builder /otelcontribcol_linux_arm64 /otelcontribcol
