name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paulgrav/opentelemetry-collector:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile.contrib --tag paulgrav/opentelemetry-collector-contrib:$(date +%s)
